# Generated by Django 5.2.11 on 2026-02-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='customuser',
            name='legacy_customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
