# Generated by Django 5.2.11 on 2026-02-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeraddress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='legacy_customer_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('warehouse', 'Warehouse'), ('admin', 'Admin')], default='owner', max_length=20),
        ),
    ]
