# Generated by Django 5.2.11 on 2026-02-28 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_addressid_to_orders'),
        ('products', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='CustomerID', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='compare_items', to='products.customer')),
                ('product', models.ForeignKey(db_column='ProductID', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'CompareList',
                'ordering': ['-added_at'],
                'managed': True,
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
