# Generated by Django 5.0.14 on 2026-05-06 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_orderdetail_variants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(db_column='CartID', primary_key=True, serialize=False)),
                ('order_count', models.IntegerField(db_column='OrderCount', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(db_column='OrderDetailID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'OrderDetails',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('discount_percent', models.DecimalField(db_column='DiscountPercent', decimal_places=2, default=0, max_digits=5)),
                ('payable_amount', models.DecimalField(blank=True, db_column='PayableAmount', decimal_places=2, max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True, db_column='PaidAt')),
            ],
            options={
                'db_table': 'Payments',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(db_column='ReviewID', primary_key=True, serialize=False)),
                ('rating', models.DecimalField(db_column='Rating', decimal_places=1, max_digits=2)),
                ('comment', models.CharField(blank=True, db_column='Comment', default='', max_length=255)),
                ('review_date', models.DateTimeField(auto_now_add=True, db_column='ReviewDate')),
            ],
            options={
                'db_table': 'Reviews',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(db_column='WishlistID', primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, db_column='AddedAt')),
            ],
            options={
                'db_table': 'Whishlist',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='free_delivery',
            field=models.BooleanField(default=False, help_text='Waive delivery charge when this coupon is applied'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='OwnerID', db_constraint=False, help_text='The store owner this coupon belongs to. Null = platform-wide (admin only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='per_customer_limit',
            field=models.IntegerField(default=1, help_text='Max times one customer can use this coupon'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('order_update', 'Order Update'), ('purchase_order', 'Purchase Order'), ('product_qa', 'Product Q&A'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
