# Generated by Django 5.0.14 on 2026-05-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(db_column='PurchaseOrderID', primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, db_column='OrderDate')),
                ('total_amount', models.DecimalField(blank=True, db_column='TotalAmount', decimal_places=2, max_digits=10, null=True)),
                ('expected_delivery_date', models.DateTimeField(blank=True, db_column='ExpectedDeliveryDate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'PurchaseOrders',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.AutoField(db_column='PurchaseOrderDetailID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('unit_cost', models.DecimalField(db_column='UnitCost', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'PurchaseOrderDetails',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
