# Generated by Django 5.2.11 on 2026-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('phone', models.CharField(blank=True, db_column='Phone', default='', max_length=20)),
                ('gender', models.CharField(blank=True, db_column='Gender', default='', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('registration_date', models.DateTimeField(blank=True, db_column='RegistrationDate', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=128, null=True)),
            ],
            options={
                'db_table': 'Customers',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': False},
        ),
    ]
