# Generated by Django 5.2.11 on 2026-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customer_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(db_column='ReviewID', primary_key=True, serialize=False)),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=1, max_digits=3, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ReviewDate')),
            ],
            options={
                'db_table': 'Reviews',
                'managed': False,
            },
        ),
    ]
