# Generated by Django 5.0.14 on 2026-05-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_market_price_snapshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'ordering': ['id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
