# Generated by Django 5.2.11 on 2026-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_auditlog_options_alter_auditlog_record_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='new_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
